const axios = require('axios');

const postRequest = async (data, headers, url) => {
    return await axios({
        method: "POST",
        url,
        headers,
        data
    });
}

const getRequest = async (api) => {
    return await axios({
        method: "GET",
        url: api,
        headers: {
            'Content-Type': 'application/json',
        },
    });
}
const COUNTRIES = {
    dubai: 'DU',
    bali: 'IO',
    egypt: 'EG',
    india: 'IND',
    greece: 'GR',
    kenya: 'KE',
    'south africa': 'SO',
    malaysia: 'MA',
    maldives: 'ML',
    israel: 'IS',
    morocco: 'MO',
    singapore: 'SI',
    spain: 'SP',
    'sri lanka': 'SR',
    thailand: 'TH',
    turkey: 'TU',
    vietnam: 'VI',
    japan: 'JP',
    italy: 'IT',
    france: 'FR',
    portugal: 'POT',
    jordan: 'JO',
    ghana: 'GHA',
    nepal: 'NEP',
    philippines: 'PHL',
    indonesia: 'IO',
    austria: 'AST',
    croatia: 'Croatia',
    australia: 'AUS',
    'new zealand': 'NZD',
    england: 'ENG',
    mauritius: 'MR',
    'french polynesia': 'FP',
    tanzania: 'TZ',
    iceland: 'ICE',
    zimbabwe: 'ZWE',
    ireland: 'IR',
    switzerland: 'SWZ',
    senegal: 'Sene',
    togo: 'Togo',
    benin: 'Ben'
}

const stopwordList = [
    'about',
    'after',
    'all',
    'also',
    'am',
    'an',
    'and',
    'another',
    'any',
    'are',
    'as',
    'at',
    'be',
    'because',
    'been',
    'before',
    'being',
    'between',
    'both',
    'but',
    'by',
    'came',
    'can',
    'come',
    'could',
    'did',
    'do',
    'each',
    'for',
    'from',
    'get',
    'got',
    'has',
    'had',
    'he',
    'have',
    'her',
    'here',
    'him',
    'himself',
    'his',
    'how',
    'if',
    'in',
    'into',
    'is',
    'it',
    'like',
    'many',
    'me',
    'might',
    'more',
    'most',
    'much',
    'must',
    'my',
    'never',
    'now',
    'of',
    'on',
    'only',
    'or',
    'other',
    'our',
    'out',
    'over',
    'said',
    'same',
    'should',
    'since',
    'some',
    'still',
    'such',
    'take',
    'than',
    'that',
    'the',
    'their',
    'them',
    'then',
    'there',
    'these',
    'they',
    'this',
    'those',
    'through',
    'to',
    'too',
    'under',
    'up',
    'very',
    'was',
    'way',
    'we',
    'well',
    'were',
    'what',
    'where',
    'which',
    'while',
    'who',
    'with',
    'would',
    'you',
    'your',
    'a',
    'i'
]

const context = {};

module.exports = { COUNTRIES, postRequest, getRequest, stopwordList, context };